### ISSUE TITLE
Akses ke halaman user setelah login

### ISSUE THREAD

**Issue by ulaai** [incursio13/rk_b_12#10]
Jika user ingin ke halaman utama setelah login, maka user tinggal klik "TCari" di bagian atas halaman user. Tapi dari halaman utama jika ingin ke halaman user, belum ada link/aksesnya. Tolong diperbaiki, terima kasih.

**Comment by MHendriF** [comment]
Linknya sudah diperbaiki

**Comment by MHendriF** [comment]
Dikarenakan issue ini sudah selesai, maka akan kami tutup. Terimakasih.
