### ISSUE TITLE
Menu yang tidak ada guna nya

### ISSUE THREAD

**Issue by ivaldyp** [incursio13/rk_b_12#11]
Pada halaman admin, pada menu "Barang Hilang" dan "Barang Temuan", terdapat sub-menu "List" yang tidak ada gunanya

**Comment by incursio13** [comment]
mohon maaf sebelumnya mungkin anda belum mendownload versi yang baru, mohon dicek kembali 
terimakasih.

**Comment by MHendriF** [comment]
Dikarenakan issue ini sudah selesai, maka akan kami tutup. Terimakasih.
