### ISSUE TITLE
Menu Message

### ISSUE THREAD

**Issue by ulaai** [incursio13/rk_b_12#12]
Ada beberapa tanggapan:

- Pada menu Compose, saat tombol Send ditekan tidak terjadi apa-apa (setidaknya diroute ke halaman lain)
- Menu Send Message sedikit membingungkan karena mirip dengan Compose, sebaiknya diganti menjadi Sent atau yang sejenisnya
![image](https://cloud.githubusercontent.com/assets/10231619/26340603/8a528bba-3fb9-11e7-8774-9fbaf3866c12.png)
- Tambahan, mungkin bahasanya bisa lebih konsisten, jika ada menu "Barang Hilang" mungkin Message bisa diganti menjadi "Pesan", atau sebaliknya jika ingin menggunakan bahasa inggris "Lost Items" dan sebagainya. 
Terima kasih

**Comment by MHendriF** [comment]
Terimakasih atas sarannya, akan kami perbaiki secepatnya

**Comment by MHendriF** [comment]
Untuk menu pesan sudah diperbaiki, silahkan dicek terimakasih.

**Comment by MHendriF** [comment]
Dikarenakan issue ini sudah selesai, maka akan kami tutup. Terimaksih.
