### ISSUE TITLE
Popup Untuk Mengirim Pesan

### ISSUE THREAD

**Issue by faishal15** [incursio13/rk_b_12#13]
Untuk mengirim pesan tolong untuk bisa di pop-up formnya ketika list ditampilkan seperti ini, bisa dengan diberi tombol Hubungi maka akan menampilkan pop-up form pesan, dan juga ikon kaca pembesar mungkin bisa diganti dengan nama barang atau ditiadakan saja namun ketika di klik gambarnya bisa menampilkan informasi terkait barang. Berikut saya sertakan gambarnya
![image](https://cloud.githubusercontent.com/assets/15714950/26504945/f4e9a684-4270-11e7-92b6-63aad8f2a99b.png)

**Comment by incursio13** [comment]
untuk mengirim pesan sudah ditambah, 
tampilan sudah diperbaiki
terimakasih

**Comment by MHendriF** [comment]
tampilan halaman barang hilang, barang temuan, cari barang hilang / temuan sudah diperbaharui, silahkan diunduh untuk mendapakan versi terbaru. Terimakasih.
