### ISSUE TITLE
Perbaikan Terkait Tampilan Halaman Depan

### ISSUE THREAD

**Issue by faishal15** [incursio13/rk_b_12#2]
Setelah kami coba jalankan, tampilan halaman depan sistem sudah cukup baik namun ada beberapa perbaikan yang ingin kami lakukan diantaranya : 
- Search bar tidak usah terlalu panjang
- Pada bagian pop-up login form juga tidak usah terlalu lebar.

Untuk halaman depan, perbaikannya menurut saya mungkin anggota tim saya yang lain bisa menambahkan, terima kasih.

**Comment by incursio13** [comment]
baik akan segera kami perbaiki

**Comment by MHendriF** [comment]
Dikarenakan issue ini sudah selesai, maka akan kami tutup. Terimaksih.
