### ISSUE TITLE
Terkait halaman pada folder "Backend"

### ISSUE THREAD

**Issue by ivaldyp** [incursio13/rk_b_12#3]
Setelah kami coba dijalankan, terdapat beberapa hal yang mungkin agak kurang dan dapat sedikit diperbaiki, antara lain:

- tampilan dan tulisan "home" dan "selamat datang" ditengah mungkin agak terlalu datar (polos). Mungkin diberi hiasan lain atau diganti atau dihapus.

- Mungkin akan lebih baik bila search bar ditampilkan ditengah halaman. 

Sekian, terima kasih

**Comment by MHendriF** [comment]
Terimakasih atas masukannnya, untuk halaman home nanti kami akan perbaiki.

**Comment by MHendriF** [comment]
halaman Home sudah diperbaharui dan search bar sudah dihapus. Silahkan bisa dicek, terimakasih.

**Comment by incursio13** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
