### ISSUE TITLE
Terkait halaman pada folder "template2"

### ISSUE THREAD

**Issue by ivaldyp** [incursio13/rk_b_12#4]
Setelah kami coba dijalankan, mungkin akan agak lebih baik apabila ditambahkan nama barang dan sedikit deskripsi barang pada bagian barang hilang. Tidak hanya gambar barangnya saja.

Sekian, terima kasih

**Comment by incursio13** [comment]
Terimakasih atas sarannya, perbaikan sudah dilakukan, mohon dicek kembali

**Comment by ulaai** [comment]
Perbaikan yang dimaksud itu pop-up description pada saat menampilkan gambar ya?

**Comment by incursio13** [comment]
iya

**Comment by incursio13** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
