### ISSUE TITLE
Form tambah barang hilang

### ISSUE THREAD

**Issue by incursio13** [incursio13/rk_b_12#6]
Halaman form untuk menambah barang hilang

**Comment by ulaai** [comment]
- Field input untuk lokasi bentuknya password, mohon diganti
- Trus ini kan yg login admin, mungkin untuk diformnya bisa ditambah nama user yang bersangkutan (kan yg menambahkan admin)

Terima kasih :)

**Comment by incursio13** [comment]
terima kasih atas masukkannya, perbaikan sudah dilakukan, mohon dicek kembali

**Comment by incursio13** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
