### ISSUE TITLE
Form Tambah User

### ISSUE THREAD

**Issue by incursio13** [incursio13/rk_b_12#7]
Halaman form untuk menambah user

**Comment by ulaai** [comment]
Untuk user akan lebih baik jika bisa upload gambar user.
Terima kasih :)

**Comment by incursio13** [comment]
terima kasih atas masukkannya, perbaikan sudah dilakukan, mohon dicek kembali

**Comment by incursio13** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
