### ISSUE TITLE
Terkait Pengelolaan Pesan

### ISSUE THREAD

**Issue by faishal15** [incursio13/rk_b_12#8]
Untuk pengelolaan pesan beberapa tampilan sudah bagus namun ada sedikit perbaikan

- Untuk setiap pesan sebaiknya ada tombol hapus di supaya tidak perlu untuk diceklist terlebih dahulu baru dihapus
- Untuk fitur send message sendiri juga lebih baik jika dapat dilakukan pada halaman paling depan sistem dimana ketika terdapat tampilan barang-barang hilang dan temuan terdapat tombol kirim pesan yang nantinya akan menampilan form untuk mengirimkan pesan kepada orang yang memposting barang yang dipilih tersebut.

Terima kasih.

**Comment by MHendriF** [comment]
Terimakasih sarannya. 

- Untuk poin yang pertama dari saran yang diberikan, saya ingin bertanya terlebih dahulu apakah nanti jika user ingin menghapus pesan harus menghapus satu persatu, atau dapat menghapus beberapa pesan secara sekaligus?

- Untuk poin kedua, bukankah user harus login dahulu untuk dapat mengirimkan pesan. Sehingga kami mengambil kesimpulan unutk menaruh fitur search pada menu user.

**Comment by ulaai** [comment]
- Jika bisa multiple delete lebih bagus.
- Maksudnya adalah ada tombol untuk instant access dari halaman barang, jadi tidak perlu ke halaman user jika ingin kirim pesan.

**Comment by MHendriF** [comment]
Untuk poin yang kedua itu maksudnya halaman barang yang ada di halaman awal atau yang di menu barang hilang / menu barang temuan mbak @ulaai ?

**Comment by MHendriF** [comment]
Pertanyaannya sudah terjawab pada issue "Popup Untuk Mengirim Pesan" silahkan di cek kembali, terimakasih.
