### ISSUE TITLE
Terkait halaman setelah login

### ISSUE THREAD

**Issue by ivaldyp** [incursio13/rk_b_12#9]
Terdapat kolom untuk pencarian pada bagian atas kiri halaman dibawah gambar admin. Kira-kira apa kegunaan pencarian tersebut karena tidak ada penjelasan. Akan lebih baik apabila kolom pencarian tersebut diberi penjelasan akan kegunaannya atau dihapus saja.

Terima kasih.

**Comment by MHendriF** [comment]
Baik terimakasih pak ivaldy sarannya sangat bagus

**Comment by ulaai** [comment]
Itu kolom pencarian tapi belum bisa dipakai ya?

**Comment by incursio13** [comment]
kolom pencarian sudah dihapus

**Comment by incursio13** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
